
#**
#* 2007-2019 Frédéric BENOIST
#*
#* NOTICE OF LICENSE
#*
#* This source file is subject to the Academic Free License (AFL 3.0)
#* that is bundled with this package in the file LICENSE.txt.
#* It is also available through the world-wide-web at this URL:
#* http://opensource.org/licenses/afl-3.0.php
#* If you did not receive a copy of the license and are unable to
#* obtain it through the world-wide-web, please send an email
#* to license@prestashop.com so we can send you a copy immediately.
#*
#*  @author    Frédéric BENOIST
#*  @copyright 2013-2019 Frédéric BENOIST <https://www.fbenoist.com/>
#*  @license   http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
#*/

# Routings
#   _legacy_controller use form tab managment
#   _legacy_link required for user right managment

fbsample_messageoftheday:
    path:     /sorep_rgpd/index
    methods:  [GET]
    defaults:
        _controller: 'sorep\sorep_rgpd\Controller\Admin\sorep_rgpdController::indexAction'
        _legacy_controller: 'sorep_rgpdClass'
        _legacy_link: 'sorep_rgpdClass'

fbsample_messageoftheday_ajax:
    path:     /sorep_rgpd/ajax/index
    methods:  [GET]
    defaults:
        _controller: 'sorep\sorep_catalopgslider\Controller\Admin\sorep_rgpdController::ajaxAction'
        _legacy_controller: 'sorep_rgpdClass'
        _legacy_link: 'sorep_rgpdClass'